### ISSUE TITLE
Request to provide a non-alpine gerrit container

### ISSUE THREAD

**Issue by raghavendrapj** [openfrontier/docker-gerrit#84]
This is not an issue, more of a feature request. 

Is there a plan to provide a non-alpine solution for the gerrit installation may be based on jdk-slim, because of some licensing issues we cannot use your alpine solution.

Or if there's one already please point me to that.

**Comment by thinkernel** [comment]
Hi @raghavendrapj 
Would you mind tell me what kind of license issue which prevent you using this image? I ask because this the first time I heard of license issue on alpine.

About your request. I think it's not a big deal to add another jdk support. Although I need to add another branch and tag for it. Dose the [ openjdk:8-jre-slim](https://github.com/docker-library/openjdk/blob/a893fe3cd82757e7bccc0948c88bfee09bd916c3/8-jre/slim/Dockerfile) fit your needs?

**Comment by raghavendrapj** [comment]
I am not sure on the specifics its something to do with redistribution of busy-box based containers.

Yes the  [openjdk:8-jre-slim]([url](https://github.com/docker-library/openjdk/blob/a893fe3cd82757e7bccc0948c88bfee09bd916c3/8-jre/slim/Dockerfile))  should be fine.

Thanks much.

**Comment by thinkernel** [comment]
@raghavendrapj 
The jre-slim based one is here -> openfrontier/gerrit:jre-slim .
Please, let me know if it works for you.

**Comment by raghavendrapj** [comment]
I will verify the same and keep posted on the results.

Thanks for this quick turnout.
