### ISSUE TITLE
[Feature Request] Use Oracle JDK instead of Open JDK

### ISSUE THREAD

**Issue by abilun** [openfrontier/docker-gerrit#85]
Is there is an explicit reason to use Open JDK instead of Oracle JDK?
Oracle JDK is showing much better performance now, it's might be a good idea to use an Oracle version.

**Comment by thinkernel** [comment]
Hi @abilun 
By saying Oracle JDK, did you mean using [oracle/openjdk](https://hub.docker.com/r/oracle/openjdk/) as the base image? The original reason I use OpenJDK instead of Oracle JDK might because there wasn't an oracle JDK image for me when I started this project. However, I have a look at the oracle/openjdk since you mentioned it. I found the size of the image is bigger because java-1.8.0-openjdk-devel is used and it's based on oraclelinux which means I have to use yum to install extra packages. I'm not a big fun of the yum. And I don't want to install jre in my own image because I have no time to deal with the upgrade of java. 
About the better performance of Oracle JDK, would you please give me some references because I really don't know that.

**Comment by kallisti5** [comment]
-1.  It is a pain to get the Oracle JRE easily in an automated fashion.  (all their licensing crap)
Gerrit runs pretty well with OpenJDK, so why add the complexity?

As for oracle/openjdk ... as the name states, that's oracle linux + open jdk.  Oracle themselves publish OpenJDK :-)
